id = "sageveil"
name = "Sageveil"
version = "0.2.2"
schema_version = 1
authors = ["sageveil"]
description = "A minimalist low-contrast, green-tinted colorscheme."
repository = "https://github.com/sageveil/zed"

[themes]
"Sageveil" = "themes/sageveil.json"
